import { City } from '@/types';

const commonWeather = (base: number[]): City['weather'] => [
  { month: '1월', avgTemp: base[0], rainfall: 20 },
  { month: '2월', avgTemp: base[0] + 2, rainfall: 25 },
  { month: '3월', avgTemp: base[0] + 8, rainfall: 45 },
  { month: '4월', avgTemp: base[0] + 14, rainfall: 70 },
  { month: '5월', avgTemp: base[0] + 19, rainfall: 85 },
  { month: '6월', avgTemp: base[0] + 23, rainfall: 150 },
  { month: '7월', avgTemp: base[0] + 26, rainfall: 280 },
  { month: '8월', avgTemp: base[0] + 27, rainfall: 260 },
  { month: '9월', avgTemp: base[0] + 22, rainfall: 140 },
  { month: '10월', avgTemp: base[0] + 15, rainfall: 50 },
  { month: '11월', avgTemp: base[0] + 8, rainfall: 35 },
  { month: '12월', avgTemp: base[0] + 2, rainfall: 20 },
];

export const ALL_CITIES: City[] = [
  {
    id: 'busan',
    slug: 'busan',
    name: '부산',
    region: '부산광역시',
    regionGroup: '경상',
    imageUrl: 'https://images.unsplash.com/photo-1583417267826-aebc4d1542e1?w=800&h=600&fit=crop',
    rating: 4.5,
    reviewCount: 203,
    monthlyCostMin: 130,
    monthlyCostMax: 200,
    internetSpeed: 312,
    tags: ['도심', '바다', '맛집'],
    rank: 1,
    description: '대한민국 제2의 도시 부산은 해운대, 광안리 등 아름다운 해변과 도심이 조화를 이루는 노마드 최적 도시입니다. 뛰어난 인프라, 저렴한 생활비, 다양한 코워킹 스페이스가 매력입니다.',
    pros: ['서울 대비 저렴한 생활비', '바다와 도심의 조화', '활발한 노마드 커뮤니티', 'KTX로 서울 2시간 30분'],
    cons: ['여름 태풍 영향', '서울 대비 적은 네트워킹 기회', '대중교통 일부 지역 불편'],
    tips: ['해운대/센텀시티 주변이 코워킹 밀집 지역입니다', '부산역 근처 게스트하우스가 장기 숙박에 유리합니다', '여름에는 해운대보다 광안리가 덜 붐빕니다'],
    images: ['https://images.unsplash.com/photo-1583417267826-aebc4d1542e1?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 40, maxPrice: 60, description: '해운대/서면 지역 원룸 기준' },
      { type: '게스트하우스', minPrice: 25, maxPrice: 40, description: '도미토리 1인실 월 기준' },
      { type: '에어비앤비', minPrice: 50, maxPrice: 90, description: '스튜디오/원룸 월 단위 할인 적용' },
    ],
    weather: commonWeather([2]),
    transportation: 'KTX(서울 2시간 30분), 지하철 4호선, 시내버스 잘 발달. 김해공항 접근 용이.',
    coworkingSpaces: [
      { id: 'bs-1', name: '해운대 코워크', price: '월 25만원 / 일 1.5만원', address: '해운대구 해운대해변로 123', rating: 4.6, facilities: ['고속와이파이', '미팅룸', '프린터', '무료커피'], hours: '08:00 - 22:00' },
      { id: 'bs-2', name: '센텀 워크스페이스', price: '월 30만원 / 일 2만원', address: '해운대구 센텀중앙로 97', rating: 4.8, facilities: ['고속와이파이', '미팅룸', '폰부스', '주차장', '카페'], hours: '24시간' },
      { id: 'bs-3', name: '서면 노마드허브', price: '월 20만원 / 일 1.2만원', address: '부산진구 중앙대로 680', rating: 4.3, facilities: ['와이파이', '미팅룸', '프린터'], hours: '09:00 - 21:00' },
    ],
  },
  {
    id: 'jeju',
    slug: 'jeju',
    name: '제주',
    region: '제주특별자치도',
    regionGroup: '제주',
    imageUrl: 'https://images.unsplash.com/photo-1598187537962-2e2fb8f6e5c4?w=800&h=600&fit=crop',
    rating: 4.7,
    reviewCount: 312,
    monthlyCostMin: 150,
    monthlyCostMax: 250,
    internetSpeed: 298,
    tags: ['자연', '힐링', '카페'],
    rank: 2,
    description: '제주도는 아름다운 자연환경과 독특한 문화가 매력적인 섬입니다. 수많은 감성 카페, 독립 서점, 코워킹 스페이스가 있어 영감을 얻으며 일하기 좋습니다.',
    pros: ['압도적인 자연환경', '다양한 감성 카페', '온화한 기후', '활발한 크리에이터 커뮤니티'],
    cons: ['서울 대비 높은 생활비', '렌터카 필수', '겨울 강풍', '육지 이동 시 항공편 필요'],
    tips: ['렌터카 없이는 생활이 불편하므로 월 렌트를 추천합니다', '제주시 연동/노형동이 생활 인프라가 좋습니다', '비수기(3~5월)에 숙소비가 저렴합니다'],
    images: ['https://images.unsplash.com/photo-1598187537962-2e2fb8f6e5c4?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 50, maxPrice: 80, description: '제주시 기준 원룸' },
      { type: '게스트하우스', minPrice: 30, maxPrice: 50, description: '도미토리/1인실 월 기준' },
      { type: '에어비앤비', minPrice: 60, maxPrice: 120, description: '스튜디오 월 단위 할인' },
    ],
    weather: commonWeather([5]),
    transportation: '제주국제공항(서울 1시간), 시내버스 있으나 배차 간격 김. 렌터카 권장.',
    coworkingSpaces: [
      { id: 'jj-1', name: '제주 노마드베이스', price: '월 28만원 / 일 1.8만원', address: '제주시 연동 123', rating: 4.7, facilities: ['고속와이파이', '미팅룸', '루프탑', '무료커피'], hours: '08:00 - 22:00' },
      { id: 'jj-2', name: '서귀포 코워킹', price: '월 22만원 / 일 1.5만원', address: '서귀포시 중문관광로 45', rating: 4.4, facilities: ['와이파이', '미팅룸', '프린터', '오션뷰'], hours: '09:00 - 21:00' },
      { id: 'jj-3', name: '탐라 워크', price: '월 25만원 / 일 1.6만원', address: '제주시 노형동 789', rating: 4.5, facilities: ['고속와이파이', '폰부스', '카페', '주차장'], hours: '24시간' },
    ],
  },
  {
    id: 'gangneung',
    slug: 'gangneung',
    name: '강릉',
    region: '강원특별자치도',
    regionGroup: '강원',
    imageUrl: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&h=600&fit=crop',
    rating: 4.3,
    reviewCount: 156,
    monthlyCostMin: 110,
    monthlyCostMax: 180,
    internetSpeed: 276,
    tags: ['바다', '조용', '카페'],
    rank: 3,
    description: '강릉은 동해 바다와 커피 문화로 유명한 도시입니다. 조용한 환경에서 집중하며 일하기 좋고, 주말에는 바다와 산을 즐길 수 있습니다.',
    pros: ['조용한 작업 환경', '뛰어난 커피 문화', '바다와 산 접근성', '합리적인 생활비'],
    cons: ['겨울 추위', '대중교통 불편', '네트워킹 기회 적음', '먹거리 다양성 부족'],
    tips: ['교동 일대가 카페 밀집 지역입니다', 'KTX 강릉역 근처가 생활하기 편합니다', '겨울에는 난방비가 많이 나올 수 있습니다'],
    images: ['https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 35, maxPrice: 50, description: '강릉역 주변 원룸 기준' },
      { type: '게스트하우스', minPrice: 20, maxPrice: 35, description: '도미토리/1인실 월 기준' },
      { type: '에어비앤비', minPrice: 40, maxPrice: 70, description: '스튜디오 월 단위' },
    ],
    weather: commonWeather([-1]),
    transportation: 'KTX(서울 1시간 50분), 시내버스, 고속버스. 시내 이동은 버스 또는 자전거.',
    coworkingSpaces: [
      { id: 'gn-1', name: '강릉 씨사이드 워크', price: '월 20만원 / 일 1.2만원', address: '강릉시 경포로 456', rating: 4.5, facilities: ['고속와이파이', '오션뷰', '무료커피', '미팅룸'], hours: '09:00 - 21:00' },
      { id: 'gn-2', name: '교동 코워킹', price: '월 18만원 / 일 1만원', address: '강릉시 교동 789', rating: 4.2, facilities: ['와이파이', '프린터', '무료커피'], hours: '09:00 - 20:00' },
    ],
  },
  {
    id: 'jeonju',
    slug: 'jeonju',
    name: '전주',
    region: '전북특별자치도',
    regionGroup: '전라',
    imageUrl: 'https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?w=800&h=600&fit=crop',
    rating: 4.4,
    reviewCount: 189,
    monthlyCostMin: 100,
    monthlyCostMax: 160,
    internetSpeed: 289,
    tags: ['맛집', '전통', '저렴'],
    rank: 4,
    description: '전주는 한옥마을과 비빔밥으로 유명한 문화 도시입니다. 저렴한 생활비와 풍부한 먹거리, 전통과 현대가 조화된 분위기가 매력입니다.',
    pros: ['매우 저렴한 생활비', '풍부한 먹거리', '전통 문화 체험', '따뜻한 지역 커뮤니티'],
    cons: ['코워킹 스페이스 적음', '네트워킹 기회 부족', '서울 접근성', '여름 무더위'],
    tips: ['한옥마을 근처보다 혁신도시 쪽이 생활하기 편합니다', '전주 비빔밥은 관광지 말고 로컬 식당을 추천합니다', 'KTX 전주역에서 시내까지 버스 20분'],
    images: ['https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 25, maxPrice: 40, description: '전주 시내 원룸 기준' },
      { type: '게스트하우스', minPrice: 18, maxPrice: 30, description: '한옥마을 주변 게스트하우스' },
      { type: '에어비앤비', minPrice: 35, maxPrice: 60, description: '한옥스테이/원룸 월 단위' },
    ],
    weather: commonWeather([0]),
    transportation: 'KTX(서울 1시간 30분), 시내버스, 고속버스. 시내 이동은 버스.',
    coworkingSpaces: [
      { id: 'jj-1', name: '전주 크리에이티브 랩', price: '월 15만원 / 일 0.8만원', address: '전주시 완산구 전주객사3길 22', rating: 4.3, facilities: ['와이파이', '미팅룸', '프린터', '무료커피'], hours: '09:00 - 21:00' },
      { id: 'jj-2', name: '혁신도시 워크센터', price: '월 18만원 / 일 1만원', address: '전주시 덕진구 혁신로 100', rating: 4.1, facilities: ['고속와이파이', '미팅룸', '주차장'], hours: '08:00 - 22:00' },
    ],
  },
  {
    id: 'seoul',
    slug: 'seoul',
    name: '서울',
    region: '서울특별시',
    regionGroup: '수도권',
    imageUrl: 'https://images.unsplash.com/photo-1546874177-9e664107314e?w=800&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 487,
    monthlyCostMin: 180,
    monthlyCostMax: 300,
    internetSpeed: 342,
    tags: ['도심', '편의시설', '네트워킹'],
    rank: 5,
    description: '대한민국의 수도 서울은 최고의 인프라와 네트워킹 기회를 제공합니다. 수많은 코워킹 스페이스, 카페, 편의시설이 밀집해 있어 불편함 없이 노마드 생활이 가능합니다.',
    pros: ['최고의 인프라', '풍부한 네트워킹 기회', '다양한 코워킹 스페이스', '국제 접근성'],
    cons: ['높은 생활비', '혼잡한 도심', '높은 주거비', '스트레스'],
    tips: ['성수동/연남동이 노마드 핫플레이스입니다', '코워킹 패스를 활용하면 저렴하게 이용 가능합니다', '지하철 이용 시 출퇴근 시간을 피하세요'],
    images: ['https://images.unsplash.com/photo-1546874177-9e664107314e?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 60, maxPrice: 100, description: '강남/마포 지역 원룸 기준' },
      { type: '게스트하우스', minPrice: 35, maxPrice: 55, description: '도미토리/1인실 월 기준' },
      { type: '에어비앤비', minPrice: 80, maxPrice: 150, description: '스튜디오 월 단위 할인' },
    ],
    weather: commonWeather([-2]),
    transportation: '지하철 9호선 + 수많은 버스. 김포/인천공항 접근 용이. 택시 저렴.',
    coworkingSpaces: [
      { id: 'sl-1', name: '위워크 성수', price: '월 40만원 / 일 3만원', address: '성동구 연무장길 11', rating: 4.8, facilities: ['고속와이파이', '미팅룸', '폰부스', '카페', '이벤트공간'], hours: '24시간' },
      { id: 'sl-2', name: '패스트파이브 강남', price: '월 35만원 / 일 2.5만원', address: '강남구 테헤란로 123', rating: 4.6, facilities: ['고속와이파이', '미팅룸', '주차장', '카페'], hours: '24시간' },
      { id: 'sl-3', name: '연남동 노마드카페', price: '월 15만원 / 일 1만원', address: '마포구 연남로 45', rating: 4.4, facilities: ['와이파이', '무료커피', '테라스'], hours: '09:00 - 23:00' },
    ],
  },
  {
    id: 'sokcho',
    slug: 'sokcho',
    name: '속초',
    region: '강원특별자치도',
    regionGroup: '강원',
    imageUrl: 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800&h=600&fit=crop',
    rating: 4.2,
    reviewCount: 134,
    monthlyCostMin: 95,
    monthlyCostMax: 170,
    internetSpeed: 267,
    tags: ['바다', '산', '조용'],
    rank: 6,
    description: '속초는 설악산과 동해 바다가 만나는 자연 친화적 도시입니다. 조용한 환경에서 집중하며 일하기 좋고, 주말에는 등산과 바다를 동시에 즐길 수 있습니다.',
    pros: ['설악산과 바다', '조용한 환경', '저렴한 생활비', '신선한 해산물'],
    cons: ['겨울 강추위', '대중교통 불편', 'IT 인프라 부족', '코워킹 적음'],
    tips: ['속초시외버스터미널 주변이 생활하기 편합니다', '겨울 난방비를 고려하세요', '주중에 설악산을 방문하면 한적합니다'],
    images: ['https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 30, maxPrice: 45, description: '속초 시내 원룸 기준' },
      { type: '게스트하우스', minPrice: 18, maxPrice: 30, description: '도미토리/1인실 월 기준' },
      { type: '에어비앤비', minPrice: 35, maxPrice: 65, description: '바다뷰 스튜디오' },
    ],
    weather: commonWeather([-3]),
    transportation: '고속버스(서울 2시간 30분), 시내버스. 자가용 또는 렌터카 권장.',
    coworkingSpaces: [
      { id: 'sc-1', name: '속초 바다워크', price: '월 15만원 / 일 1만원', address: '속초시 청초호반로 12', rating: 4.3, facilities: ['와이파이', '오션뷰', '무료커피'], hours: '09:00 - 20:00' },
    ],
  },
  {
    id: 'daejeon',
    slug: 'daejeon',
    name: '대전',
    region: '대전광역시',
    regionGroup: '충청',
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
    rating: 4.1,
    reviewCount: 142,
    monthlyCostMin: 100,
    monthlyCostMax: 170,
    internetSpeed: 305,
    tags: ['도심', '저렴', '교통편리'],
    description: '대전은 대한민국 중심부에 위치한 과학 도시입니다. KTX로 서울까지 50분, 합리적인 생활비와 빠른 인터넷이 장점입니다.',
    pros: ['KTX 서울 50분', '저렴한 생활비', '빠른 인터넷', '대덕연구단지 IT 인프라'],
    cons: ['관광 명소 부족', '야간 활동 제한', '식당 다양성 부족'],
    tips: ['유성구가 연구원/노마드들에게 인기 지역입니다', '둔산동이 상권이 가장 발달했습니다', 'KTX를 활용해 서울 미팅도 당일치기 가능합니다'],
    images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 30, maxPrice: 45, description: '유성/둔산 지역 원룸' },
      { type: '게스트하우스', minPrice: 20, maxPrice: 32, description: '월 기준' },
      { type: '에어비앤비', minPrice: 40, maxPrice: 65, description: '스튜디오 월 단위' },
    ],
    weather: commonWeather([-1]),
    transportation: 'KTX(서울 50분), 지하철 1호선, 시내버스. 교통 편리.',
    coworkingSpaces: [
      { id: 'dj-1', name: '유성 코워킹허브', price: '월 18만원 / 일 1.2만원', address: '유성구 대학로 99', rating: 4.2, facilities: ['고속와이파이', '미팅룸', '주차장'], hours: '08:00 - 22:00' },
      { id: 'dj-2', name: '둔산 워크스페이스', price: '월 20만원 / 일 1.3만원', address: '서구 둔산로 201', rating: 4.0, facilities: ['와이파이', '미팅룸', '프린터', '무료커피'], hours: '09:00 - 21:00' },
    ],
  },
  {
    id: 'daegu',
    slug: 'daegu',
    name: '대구',
    region: '대구광역시',
    regionGroup: '경상',
    imageUrl: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=800&h=600&fit=crop',
    rating: 4.0,
    reviewCount: 128,
    monthlyCostMin: 95,
    monthlyCostMax: 165,
    internetSpeed: 295,
    tags: ['도심', '저렴', '맛집'],
    description: '대구는 분지 지형의 따뜻한 도시로, 저렴한 생활비와 발달한 도심 인프라가 특징입니다. 동성로 중심의 활발한 상권과 다양한 먹거리가 매력입니다.',
    pros: ['매우 저렴한 생활비', '따뜻한 기후', '발달한 도심', '다양한 먹거리'],
    cons: ['여름 폭염', '관광 자원 부족', '바다 없음', '코워킹 적음'],
    tips: ['동성로/수성구가 생활하기 좋습니다', '여름에는 40도까지 올라가니 에어컨 필수입니다', '앞산공원에서 야간 산책을 추천합니다'],
    images: ['https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 25, maxPrice: 40, description: '동성로/수성구 원룸' },
      { type: '게스트하우스', minPrice: 18, maxPrice: 28, description: '월 기준' },
      { type: '에어비앤비', minPrice: 35, maxPrice: 55, description: '스튜디오 월 단위' },
    ],
    weather: commonWeather([0]),
    transportation: 'KTX(서울 1시간 40분), 지하철 3호선, 시내버스.',
    coworkingSpaces: [
      { id: 'dg-1', name: '동성로 코워크', price: '월 16만원 / 일 1만원', address: '중구 동성로 55', rating: 4.1, facilities: ['와이파이', '미팅룸', '무료커피'], hours: '09:00 - 21:00' },
      { id: 'dg-2', name: '수성 워크플레이스', price: '월 20만원 / 일 1.3만원', address: '수성구 범어로 123', rating: 4.3, facilities: ['고속와이파이', '미팅룸', '폰부스', '주차장'], hours: '08:00 - 22:00' },
    ],
  },
  {
    id: 'gwangju',
    slug: 'gwangju',
    name: '광주',
    region: '광주광역시',
    regionGroup: '전라',
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop',
    rating: 4.2,
    reviewCount: 115,
    monthlyCostMin: 90,
    monthlyCostMax: 155,
    internetSpeed: 288,
    tags: ['예술', '맛집', '저렴'],
    description: '광주는 예술과 문화의 도시입니다. 전남대/조선대 주변 활기찬 분위기, 저렴한 생활비, 풍부한 남도 음식이 매력입니다.',
    pros: ['매우 저렴한 생활비', '풍부한 예술/문화', '남도 음식 천국', '활기찬 대학가'],
    cons: ['서울 접근성', '코워킹 스페이스 부족', '대중교통 일부 불편'],
    tips: ['충장로/상무지구가 생활 중심입니다', '전남대 주변 카페가 작업하기 좋습니다', 'SRT로 서울까지 1시간 40분입니다'],
    images: ['https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 22, maxPrice: 38, description: '상무/충장로 원룸' },
      { type: '게스트하우스', minPrice: 15, maxPrice: 25, description: '월 기준' },
      { type: '에어비앤비', minPrice: 30, maxPrice: 50, description: '스튜디오 월 단위' },
    ],
    weather: commonWeather([1]),
    transportation: 'SRT/KTX(서울 1시간 40분), 시내버스, 지하철 1호선.',
    coworkingSpaces: [
      { id: 'gj-1', name: '광주 크리에이티브 허브', price: '월 14만원 / 일 0.8만원', address: '동구 충장로 88', rating: 4.2, facilities: ['와이파이', '미팅룸', '무료커피'], hours: '09:00 - 21:00' },
    ],
  },
  {
    id: 'yeosu',
    slug: 'yeosu',
    name: '여수',
    region: '전라남도',
    regionGroup: '전라',
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&h=600&fit=crop',
    rating: 4.4,
    reviewCount: 97,
    monthlyCostMin: 100,
    monthlyCostMax: 170,
    internetSpeed: 258,
    tags: ['바다', '힐링', '맛집'],
    description: '여수는 아름다운 남해 바다와 밤바다로 유명한 관광 도시입니다. 해안도로를 따라 산책하며 영감을 얻고, 신선한 해산물을 즐길 수 있습니다.',
    pros: ['아름다운 야경', '신선한 해산물', '온화한 기후', '힐링 환경'],
    cons: ['인터넷 속도 보통', '코워킹 부족', '서울 접근성', '관광 시즌 혼잡'],
    tips: ['비수기에 방문하면 조용하게 작업할 수 있습니다', '여수엑스포역 근처가 생활 편의성이 좋습니다', '돌산대교 야경은 꼭 보세요'],
    images: ['https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 30, maxPrice: 45, description: '여수 시내 원룸' },
      { type: '게스트하우스', minPrice: 20, maxPrice: 35, description: '월 기준' },
      { type: '에어비앤비', minPrice: 40, maxPrice: 70, description: '오션뷰 스튜디오' },
    ],
    weather: commonWeather([3]),
    transportation: 'KTX(서울 2시간 50분), 시내버스, 고속버스.',
    coworkingSpaces: [
      { id: 'ys-1', name: '여수 오션워크', price: '월 16만원 / 일 1만원', address: '여수시 오동도로 33', rating: 4.3, facilities: ['와이파이', '오션뷰', '무료커피'], hours: '09:00 - 20:00' },
    ],
  },
  {
    id: 'chuncheon',
    slug: 'chuncheon',
    name: '춘천',
    region: '강원특별자치도',
    regionGroup: '강원',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop',
    rating: 4.1,
    reviewCount: 108,
    monthlyCostMin: 85,
    monthlyCostMax: 150,
    internetSpeed: 272,
    tags: ['자연', '저렴', '조용'],
    description: '춘천은 호수와 산이 어우러진 자연 도시입니다. 서울에서 ITX로 1시간 거리로 접근성이 좋고, 매우 저렴한 생활비가 장점입니다.',
    pros: ['서울 근접(ITX 1시간)', '매우 저렴한 생활비', '아름다운 호수 환경', '낮은 인구밀도'],
    cons: ['겨울 강추위', '야간 문화 부족', '코워킹 적음', '먹거리 제한'],
    tips: ['의암호 주변 카페에서 작업하면 분위기가 좋습니다', '닭갈비 말고도 막국수도 유명합니다', '겨울에는 영하 20도까지 내려가니 방한 준비 필수'],
    images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 22, maxPrice: 35, description: '춘천역 주변 원룸' },
      { type: '게스트하우스', minPrice: 15, maxPrice: 25, description: '월 기준' },
      { type: '에어비앤비', minPrice: 30, maxPrice: 50, description: '레이크뷰 스튜디오' },
    ],
    weather: commonWeather([-5]),
    transportation: 'ITX(서울 1시간), 시내버스, 고속버스.',
    coworkingSpaces: [
      { id: 'cc-1', name: '춘천 레이크워크', price: '월 12만원 / 일 0.7만원', address: '춘천시 의암호반길 55', rating: 4.0, facilities: ['와이파이', '레이크뷰', '무료커피'], hours: '09:00 - 20:00' },
    ],
  },
  {
    id: 'sejong',
    slug: 'sejong',
    name: '세종',
    region: '세종특별자치시',
    regionGroup: '충청',
    imageUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=600&fit=crop',
    rating: 4.0,
    reviewCount: 76,
    monthlyCostMin: 95,
    monthlyCostMax: 165,
    internetSpeed: 310,
    tags: ['도심', '깨끗함', '교통편리'],
    description: '세종시는 대한민국의 행정수도로, 깨끗하고 계획적인 도시 환경이 특징입니다. 새 건물, 넓은 도로, 빠른 인터넷이 장점입니다.',
    pros: ['깨끗한 신도시 환경', '빠른 인터넷', '합리적인 생활비', 'BRT 교통 체계'],
    cons: ['문화생활 부족', '야간 활동 제한', '인구 적어 활력 부족'],
    tips: ['정부세종청사 근처에 카페가 많습니다', 'BRT(간선급행버스)로 이동하면 편합니다', '대전과 병행 생활하는 노마드도 많습니다'],
    images: ['https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 30, maxPrice: 48, description: '나성동/어진동 원룸' },
      { type: '에어비앤비', minPrice: 40, maxPrice: 65, description: '신축 스튜디오' },
    ],
    weather: commonWeather([-1]),
    transportation: 'BRT(대전 30분), 고속버스(서울 2시간), 세종~오송역(KTX).',
    coworkingSpaces: [
      { id: 'sj-1', name: '세종 스마트워크센터', price: '월 15만원 / 일 0.8만원', address: '세종시 한누리대로 2130', rating: 4.1, facilities: ['고속와이파이', '미팅룸', '주차장', '프린터'], hours: '08:00 - 22:00' },
    ],
  },
  {
    id: 'gyeongju',
    slug: 'gyeongju',
    name: '경주',
    region: '경상북도',
    regionGroup: '경상',
    imageUrl: 'https://images.unsplash.com/photo-1600298882525-1ac63b53bc85?w=800&h=600&fit=crop',
    rating: 4.3,
    reviewCount: 88,
    monthlyCostMin: 85,
    monthlyCostMax: 145,
    internetSpeed: 262,
    tags: ['전통', '조용', '힐링'],
    description: '경주는 천년 고도의 역사와 자연이 어우러진 도시입니다. 조용한 환경에서 역사 유적을 감상하며 작업하기 좋은 힐링 도시입니다.',
    pros: ['풍부한 역사 유적', '매우 저렴한 생활비', '조용한 환경', '자전거 타기 좋은 도시'],
    cons: ['인프라 부족', '코워킹 매우 적음', '대중교통 불편'],
    tips: ['황리단길 카페에서 작업하기 좋습니다', '자전거로 유적지 투어를 추천합니다', 'KTX 신경주역에서 시내까지 버스 20분'],
    images: ['https://images.unsplash.com/photo-1600298882525-1ac63b53bc85?w=800&h=600&fit=crop'],
    accommodations: [
      { type: '원룸', minPrice: 22, maxPrice: 35, description: '경주 시내 원룸' },
      { type: '게스트하우스', minPrice: 15, maxPrice: 25, description: '월 기준' },
      { type: '에어비앤비', minPrice: 30, maxPrice: 50, description: '한옥스테이/원룸' },
    ],
    weather: commonWeather([1]),
    transportation: 'KTX 신경주역(서울 2시간), 시내버스, 자전거 도로 잘 정비.',
    coworkingSpaces: [
      { id: 'gj-1', name: '황리단 코워킹', price: '월 12만원 / 일 0.7만원', address: '경주시 황남동 포석로 22', rating: 4.2, facilities: ['와이파이', '무료커피', '정원'], hours: '09:00 - 20:00' },
    ],
  },
];

export const POPULAR_CITIES = ALL_CITIES.filter((city) => city.rank).sort(
  (a, b) => (a.rank ?? 99) - (b.rank ?? 99)
);

export function getCityBySlug(slug: string): City | undefined {
  return ALL_CITIES.find((city) => city.slug === slug);
}

export function getCitiesByRegion(regionGroup: string): City[] {
  return ALL_CITIES.filter((city) => city.regionGroup === regionGroup);
}
