import { Post, Comment } from '@/types/community';

export const POSTS: Post[] = [
  {
    id: 'p1',
    title: '부산에서 한 달 살기 후기',
    content: '해운대 근처에서 한 달 동안 노마드 생활을 했습니다. 코워킹 스페이스, 맛집, 생활비 등 자세한 후기를 공유합니다. 특히 센텀 워크스페이스는 24시간 운영이라 야간 작업할 때 정말 좋았어요.',
    category: '자유',
    authorName: '부산노마드',
    authorEmail: 'busan@example.com',
    createdAt: new Date('2025-01-20'),
    commentCount: 8,
    likeCount: 24,
    tags: ['부산', '한달살기', '후기'],
  },
  {
    id: 'p2',
    title: '제주도 렌터카 없이 생활 가능한가요?',
    content: '제주도에서 한 달 살기를 계획 중인데, 렌터카 없이 대중교통만으로 생활이 가능할까요? 경험 있으신 분들의 조언 부탁드립니다.',
    category: '질문',
    authorName: '제주궁금',
    authorEmail: 'jeju@example.com',
    createdAt: new Date('2025-01-18'),
    commentCount: 12,
    likeCount: 15,
    tags: ['제주', '교통', '질문'],
  },
  {
    id: 'p3',
    title: '[정보] 전국 코워킹 스페이스 할인 패스 모음',
    content: '전국 코워킹 스페이스 할인 패스를 정리했습니다. 패스트파이브, 위워크, 스파크플러스 등 주요 코워킹의 월간/주간 패스 가격 비교 정보입니다.',
    category: '정보공유',
    authorName: '코워킹매니아',
    authorEmail: 'cowork@example.com',
    createdAt: new Date('2025-01-15'),
    commentCount: 6,
    likeCount: 42,
    tags: ['코워킹', '할인', '정보'],
  },
  {
    id: 'p4',
    title: '[모임] 강릉 노마드 번개 (2월 첫째 주)',
    content: '2월 첫째 주에 강릉에 계신 노마드 분들과 가벼운 모임을 갖고 싶습니다. 교동 카페거리에서 커피 한 잔 하면서 이야기 나눠요!',
    category: '모임',
    authorName: '강릉모임장',
    authorEmail: 'gangneung@example.com',
    createdAt: new Date('2025-01-12'),
    commentCount: 15,
    likeCount: 31,
    tags: ['강릉', '모임', '번개'],
  },
  {
    id: 'p5',
    title: '노마드 생활 필수 앱 추천',
    content: 'VPN, 환율 계산, 코워킹 검색, 숙소 예약 등 노마드 생활에 도움이 되는 앱들을 정리해봤습니다.',
    category: '정보공유',
    authorName: '앱덕후',
    authorEmail: 'appfan@example.com',
    createdAt: new Date('2025-01-10'),
    commentCount: 9,
    likeCount: 38,
    tags: ['앱', '추천', '정보'],
  },
  {
    id: 'p6',
    title: '서울 성수동 vs 연남동, 어디가 더 좋을까?',
    content: '서울에서 노마드 생활하시는 분들, 성수동과 연남동 중 어디가 더 작업하기 좋은지 의견 나눠주세요.',
    category: '자유',
    authorName: '서울러',
    authorEmail: 'seoul@example.com',
    createdAt: new Date('2025-01-08'),
    commentCount: 18,
    likeCount: 22,
    tags: ['서울', '성수', '연남'],
  },
  {
    id: 'p7',
    title: '겨울 노마드 추천 도시는?',
    content: '겨울에 따뜻하게 작업할 수 있는 도시를 추천해주세요. 제주는 바람이 너무 강하다고 들었는데...',
    category: '질문',
    authorName: '겨울이싫어',
    authorEmail: 'winter@example.com',
    createdAt: new Date('2025-01-05'),
    commentCount: 14,
    likeCount: 19,
    tags: ['겨울', '추천', '질문'],
  },
  {
    id: 'p8',
    title: '[정보] 각 도시별 1달 생활비 실비 정산',
    content: '서울, 부산, 제주, 강릉에서 각각 한 달씩 살아본 생활비를 실비로 정산해봤습니다. 숙소, 식비, 교통비, 코워킹비 등 항목별로 정리했어요.',
    category: '정보공유',
    authorName: '가계부노마드',
    authorEmail: 'budget@example.com',
    createdAt: new Date('2025-01-03'),
    commentCount: 21,
    likeCount: 56,
    tags: ['생활비', '비교', '정보'],
  },
  {
    id: 'p9',
    title: '[모임] 서울 노마드 네트워킹 데이',
    content: '매월 마지막 금요일에 성수동에서 노마드 네트워킹 모임을 진행합니다. 프리랜서, 리모트워커, 1인 사업자 모두 환영합니다!',
    category: '모임',
    authorName: '네트워킹킹',
    authorEmail: 'network@example.com',
    createdAt: new Date('2024-12-28'),
    commentCount: 25,
    likeCount: 48,
    tags: ['서울', '네트워킹', '모임'],
  },
  {
    id: 'p10',
    title: '대전에서 노마드 생활한 솔직 후기',
    content: '대전에서 3개월 동안 노마드 생활을 했습니다. KTX로 서울 50분이라 미팅 참석이 편했고, 생활비는 정말 저렴했어요. 다만 밤에 할 게 없다는 게 유일한 단점입니다.',
    category: '자유',
    authorName: '대전사랑',
    authorEmail: 'daejeon@example.com',
    createdAt: new Date('2024-12-25'),
    commentCount: 7,
    likeCount: 16,
    tags: ['대전', '후기', '생활비'],
  },
  {
    id: 'p11',
    title: '노마드 건강 관리 팁 공유',
    content: '오래 앉아서 작업하다 보면 건강이 나빠지기 쉬운데, 제가 실천하고 있는 건강 관리 루틴을 공유합니다. 스탠딩 데스크, 스트레칭, 산책 루틴 등.',
    category: '정보공유',
    authorName: '건강노마드',
    authorEmail: 'health@example.com',
    createdAt: new Date('2024-12-20'),
    commentCount: 11,
    likeCount: 33,
    tags: ['건강', '팁', '루틴'],
  },
  {
    id: 'p12',
    title: '경주 황리단길 카페 작업 후기',
    content: '경주 황리단길에서 일주일간 작업해봤는데, 카페 분위기가 정말 독특하고 좋았습니다. 한옥 카페에서 역사적인 분위기를 느끼며 작업하는 경험은 특별했어요.',
    category: '자유',
    authorName: '경주러버',
    authorEmail: 'gyeongju@example.com',
    createdAt: new Date('2024-12-15'),
    commentCount: 5,
    likeCount: 21,
    tags: ['경주', '카페', '후기'],
  },
];

export const COMMENTS: Comment[] = [
  { id: 'c1', postId: 'p1', authorName: '노마드초보', content: '정말 유용한 정보네요! 부산 가볼 때 참고하겠습니다.', createdAt: new Date('2025-01-21') },
  { id: 'c2', postId: 'p1', authorName: '부산토박이', content: '센텀시티 쪽 카페도 작업하기 좋아요. 추천합니다!', createdAt: new Date('2025-01-21') },
  { id: 'c3', postId: 'p1', authorName: '여행러', content: '저도 해운대에서 한 달 살았는데 공감합니다.', createdAt: new Date('2025-01-22') },
  { id: 'c4', postId: 'p2', authorName: '제주경험자', content: '솔직히 렌터카 없이는 힘듭니다. 제주시 시내만 돌아다니실 거면 가능하지만...', createdAt: new Date('2025-01-19') },
  { id: 'c5', postId: 'p2', authorName: '대중교통파', content: '버스 앱 잘 활용하면 가능해요! 다만 배차 간격이 길어서 시간 계획은 잘 세워야 합니다.', createdAt: new Date('2025-01-19') },
];

export function getPostById(id: string): Post | undefined {
  return POSTS.find((post) => post.id === id);
}

export function getCommentsByPostId(postId: string): Comment[] {
  return COMMENTS.filter((comment) => comment.postId === postId);
}
