import { Review } from '@/types';

export const ALL_REVIEWS: Review[] = [
  {
    id: 'r1',
    userId: 'u1',
    userNickname: '디지털노마드123',
    cityId: 'busan',
    citySlug: 'busan',
    cityName: '부산',
    rating: 5,
    content: '해운대 근처 코워킹 스페이스가 정말 좋았어요. 바다 보면서 일하는 기분이 최고입니다! 생활비도 서울보다 저렴하고, 맛집도 많아서 만족스러운 한 달이었습니다.',
    tags: ['인터넷빠름', '카페좋음', '맛집많음'],
    createdAt: new Date('2024-12-01'),
  },
  {
    id: 'r2',
    userId: 'u2',
    userNickname: '제주살이',
    cityId: 'jeju',
    citySlug: 'jeju',
    cityName: '제주',
    rating: 4,
    content: '자연 속에서 일하고 싶다면 제주가 최고예요. 다만 생활비가 생각보다 높고, 겨울에는 바람이 강해서 조금 힘들었습니다. 그래도 카페 분위기는 정말 좋아요!',
    tags: ['자연경관', '카페좋음'],
    createdAt: new Date('2024-12-05'),
  },
  {
    id: 'r3',
    userId: 'u3',
    userNickname: '강릉러버',
    cityId: 'gangneung',
    citySlug: 'gangneung',
    cityName: '강릉',
    rating: 5,
    content: '강릉은 조용하고 집중하기 좋은 도시입니다. 커피 문화가 발달해서 카페 작업하기 완벽해요. 바다와 산이 가까워 주말에 힐링하기도 좋습니다.',
    tags: ['조용함', '카페좋음', '자연경관'],
    createdAt: new Date('2024-12-10'),
  },
  {
    id: 'r4',
    userId: 'u4',
    userNickname: '서울워커',
    cityId: 'seoul',
    citySlug: 'seoul',
    cityName: '서울',
    rating: 4,
    content: '코워킹 스페이스가 정말 많아서 선택의 폭이 넓어요. 네트워킹 기회도 풍부하고, 인프라가 최고입니다. 다만 생활비가 부담되긴 합니다.',
    tags: ['인터넷빠름', '네트워킹'],
    createdAt: new Date('2024-12-15'),
  },
  {
    id: 'r5',
    userId: 'u5',
    userNickname: '전주맛집탐방',
    cityId: 'jeonju',
    citySlug: 'jeonju',
    cityName: '전주',
    rating: 5,
    content: '생활비가 정말 저렴해서 놀랐습니다. 한 달 100만원으로도 충분히 생활 가능해요. 한옥마을 분위기도 좋고, 무엇보다 먹거리가 끝내줍니다!',
    tags: ['저렴함', '맛집많음'],
    createdAt: new Date('2024-12-18'),
  },
  {
    id: 'r6',
    userId: 'u6',
    userNickname: '바다사랑',
    cityId: 'sokcho',
    citySlug: 'sokcho',
    cityName: '속초',
    rating: 4,
    content: '설악산 등산 후 바다에서 힐링하는 주말이 최고였어요. 물가도 저렴하고 해산물이 신선합니다. 다만 겨울에는 정말 춥더라고요.',
    tags: ['자연경관', '조용함', '저렴함'],
    createdAt: new Date('2024-12-20'),
  },
  {
    id: 'r7',
    userId: 'u7',
    userNickname: '과학도시노마드',
    cityId: 'daejeon',
    citySlug: 'daejeon',
    cityName: '대전',
    rating: 4,
    content: 'KTX로 서울 50분이라 미팅이 잦은 분들에게 추천합니다. 유성구 카페에서 작업하면 조용하고 좋아요. 대덕연구단지 근처 IT 인프라도 우수합니다.',
    tags: ['인터넷빠름', '교통편리'],
    createdAt: new Date('2024-12-22'),
  },
  {
    id: 'r8',
    userId: 'u8',
    userNickname: '대구탐험가',
    cityId: 'daegu',
    citySlug: 'daegu',
    cityName: '대구',
    rating: 3,
    content: '생활비는 정말 저렴해서 좋았지만, 여름 폭염이 장난 아닙니다. 에어컨 없이는 작업 불가능해요. 봄가을에 방문하는 것을 강력 추천합니다.',
    tags: ['저렴함', '맛집많음'],
    createdAt: new Date('2024-12-25'),
  },
  {
    id: 'r9',
    userId: 'u9',
    userNickname: '예술가노마드',
    cityId: 'gwangju',
    citySlug: 'gwangju',
    cityName: '광주',
    rating: 5,
    content: '광주의 예술 문화에 완전 빠졌습니다. 비엔날레 시즌에 방문하면 정말 영감을 많이 받아요. 남도 음식도 최고이고, 생활비도 착합니다.',
    tags: ['예술문화', '맛집많음', '저렴함'],
    createdAt: new Date('2024-12-28'),
  },
  {
    id: 'r10',
    userId: 'u10',
    userNickname: '여수밤바다',
    cityId: 'yeosu',
    citySlug: 'yeosu',
    cityName: '여수',
    rating: 5,
    content: '여수 밤바다는 정말 환상적이에요. 해안도로 카페에서 작업하면 영감이 샘솟습니다. 해산물도 신선하고, 힐링하기에 완벽한 도시입니다.',
    tags: ['자연경관', '힐링', '맛집많음'],
    createdAt: new Date('2025-01-02'),
  },
  {
    id: 'r11',
    userId: 'u11',
    userNickname: '호수가좋아',
    cityId: 'chuncheon',
    citySlug: 'chuncheon',
    cityName: '춘천',
    rating: 4,
    content: '의암호 주변 카페에서 호수 보며 일하는 게 정말 좋았어요. ITX로 서울 1시간이라 접근성도 괜찮습니다. 다만 겨울에는 정말정말 춥습니다.',
    tags: ['자연경관', '조용함', '저렴함'],
    createdAt: new Date('2025-01-05'),
  },
  {
    id: 'r12',
    userId: 'u12',
    userNickname: '행정수도',
    cityId: 'sejong',
    citySlug: 'sejong',
    cityName: '세종',
    rating: 3,
    content: '깨끗하고 정돈된 도시라 쾌적합니다. 인터넷도 빠르고 인프라도 새거라 좋아요. 하지만 밤에 할 게 너무 없어서 심심합니다.',
    tags: ['인터넷빠름', '깨끗함'],
    createdAt: new Date('2025-01-08'),
  },
  {
    id: 'r13',
    userId: 'u13',
    userNickname: '역사덕후',
    cityId: 'gyeongju',
    citySlug: 'gyeongju',
    cityName: '경주',
    rating: 5,
    content: '천년 고도의 분위기에서 작업하니 색다른 영감을 받았습니다. 황리단길 카페도 분위기 좋고, 자전거로 유적지 투어하는 주말이 최고였어요.',
    tags: ['조용함', '힐링', '자연경관'],
    createdAt: new Date('2025-01-12'),
  },
  {
    id: 'r14',
    userId: 'u14',
    userNickname: '부산사랑',
    cityId: 'busan',
    citySlug: 'busan',
    cityName: '부산',
    rating: 4,
    content: '센텀 워크스페이스 24시간 운영이라 야간 작업할 때 좋았습니다. 광안리 야경도 최고이고, 서면 먹자골목도 가성비 좋아요.',
    tags: ['인터넷빠름', '맛집많음', '카페좋음'],
    createdAt: new Date('2025-01-15'),
  },
  {
    id: 'r15',
    userId: 'u15',
    userNickname: '제주이주민',
    cityId: 'jeju',
    citySlug: 'jeju',
    cityName: '제주',
    rating: 5,
    content: '제주에서 3개월째 살고 있는데 정말 만족합니다. 크리에이터 커뮤니티가 활발하고, 매주 새로운 사람들을 만날 수 있어요. 렌터카는 필수입니다!',
    tags: ['자연경관', '네트워킹', '카페좋음'],
    createdAt: new Date('2025-01-20'),
  },
];

export const LATEST_REVIEWS = ALL_REVIEWS.slice(-3).reverse();

export function getReviewsByCitySlug(slug: string): Review[] {
  return ALL_REVIEWS.filter((review) => review.citySlug === slug);
}
